# config.yaml
base_course_path: "C:/Users/sgari/Documents/UdemyCourses"
obs_video_path: "C:/Users/sgari/Videos/Videos"
course_prefix: "TOUCAN_COURSE"
starting_course_number: 1
sections_per_course: 10
lectures_per_section: 5
